### ISSUE TITLE
Target isnt working

### ISSUE THREAD

**Issue by ghost** [ThatMadCap/mad-cipherheist#1]
Target isnt working in PanelHack 
Target isnt working in under water TrackedLoot

**Comment by ThatMadCap** [comment]
The targetting all works in the latest version.

What target are you using, what script errors do you have, how is your config setup? You have to provide at least this basic information before opening an issue on git.

**Comment by ghost** [comment]
Figured it out it's causing cuz of latest qb-target 
Used a lowered version and it worked fine
Great heist loved it🤟🏾
